# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 07:42
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovePass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_outTime', models.DateTimeField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('branch', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='InTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField()),
                ('approved_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.ApprovePass')),
            ],
        ),
        migrations.CreateModel(
            name='IssueCancelled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssuePass',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('outTime', models.DateTimeField()),
                ('inTime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('sem_id', models.AutoField(primary_key=True, serialize=False)),
                ('frm', models.IntegerField()),
                ('to', models.IntegerField()),
                ('no', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'sem',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('hallticket_no', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30, null=True)),
                ('student_phno', models.CharField(max_length=15, null=True)),
                ('father_phno', models.CharField(max_length=15, null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.Classes')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sem',
            unique_together=set([('frm', 'to', 'no')]),
        ),
        migrations.AddField(
            model_name='issuepass',
            name='hallticket_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.Student'),
        ),
        migrations.AddField(
            model_name='issuepass',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuecancelled',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.IssuePass'),
        ),
        migrations.AddField(
            model_name='classes',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.Sem'),
        ),
        migrations.AddField(
            model_name='approvepass',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.IssuePass'),
        ),
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together=set([('year', 'branch', 'section', 'sem')]),
        ),
    ]
