# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20171023_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvepass',
            name='real_outTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 16, 30, 1, 946076)),
        ),
        migrations.AlterField(
            model_name='intimes',
            name='in_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 16, 30, 1, 946076)),
        ),
    ]
